const Constants = {
    SET_FIVE_DAY_RESULTS: "SET_FIVE_DAY_RESULTS",

    ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
    REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
    LOAD_FAVORITES: 'LOAD_FAVORITES',
    REDIRECT_TO_FAVORITES: "SWICH_TO_FAVORITES",
    REDIRECT_TO_FIVE_DAYS: "REDIRECT_TO_FIVE_DAYS",

    SET_LOCATION_KEY: "SET_LOCATION_KEY",
    LOAD_SIGLE_WEATHER_DETAILS: "LOAD_SIGLE_WEATHER_DETAILS",
    UPDATE_SIGLE_WEATHER_DETAILS: "UPDATE_SIGLE_WEATHER_DETAILS",

    LOAD_5_DAY_WEATHER_DETAILS: "LOAD_5_DAY_WEATHER_DETAILS",
    
    UPDATE_SEARCH_TERM: "UPDATE_SEARCH_TERM",
    SUBMIT_SEARCH: "SUBMIT_SEARCH",
    UPDATE_SEARCH_RESULTS: "UPDATE_SEARCH_RESULTS",

    GET_FAVORITE_WEATHER: "GET_FAVORITE_WEATHER",
    UPDATE_FAVORITE_WEATHER: "UPDATE_FAVORITE_WEATHER",

    ERROR: "ERROR_CONSTANT",
    CLEAR_ERROR: "CLEAR_ERROR"

};

export { Constants }
