const Constants = {
    REDUCER_ACTION: "REDUCER_ACTION",
    SAGA_ACTION: "SAGA_ACTION",

    SET_FIVE_DAY_RESULTS: "SET_FIVE_DAY_RESULTS",

    ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
    REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",

};

export { Constants }
